service: node-astra-serverless

useDotenv: true

package:
  individually: true
  exclude:
    - "scripts/**"

plugins:
  - serverless-bundle
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

functions:
  list:
    handler: list.main
    events:
      - http:
          path: workouts
          method: get
  create:
    handler: create.main
    events:
      - http:
          path: workouts
          method: post
